USE chords_db;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE video_songs;
TRUNCATE mp3_songs;
TRUNCATE user_questions_sign;
TRUNCATE users_users_fav;
TRUNCATE users_singers_fav;     
TRUNCATE users_songs_fav;
TRUNCATE users_resources;
TRUNCATE singers_songs;
TRUNCATE answers;  
TRUNCATE questions;
TRUNCATE questions_categories;
TRUNCATE news;
TRUNCATE resources;
TRUNCATE chords;
TRUNCATE profiles;
TRUNCATE songs;
TRUNCATE singers;
TRUNCATE avatars;
TRUNCATE photo;
TRUNCATE video;
TRUNCATE mp3;
TRUNCATE users;
SET FOREIGN_KEY_CHECKS = 1;