insert into profiles (user_id, gender, birthday, avatar_id, country, region, city, about, send_daily, send_weekly, dont_send) values
 (241, 'x', '1961/05/26', null, 'France', 'Île-de-France', 'Paris 05', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, 1, 0),
 (242, 'f', '1994/08/23', 190, 'France', 'Midi-Pyrénées', 'Toulouse', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1, 0, 0),
 (243, 'm', '1965/11/10', 183, 'France', 'Alsace', null, null, 0, 0, 1),
 (244, 'f', '1976/07/05', 50, 'France', 'Île-de-France', null, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 1, 1, 0),
 (245, 'f', '1981/12/11', 6, 'France', 'Rhône-Alpes', 'Lyon', null, 0, 1, 0),
 (246, 'f', '1982/10/07', null, 'Germany', null, null, null, 1, 0, 0),
 (247, 'f', '2007/03/10', 88, 'France', null, null, null, 0, 0, 0),
 (248, 'x', '2003/07/19', 56, null, null, null, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 0, 0, 1),
 (249, 'x', '1998/03/20', 154, 'France', 'Provence-Alpes-Côte d''Azur', 'Nice', null, 1, 1, 0),
 (250, 'f', '1978/06/16', 50, 'France', 'Poitou-Charentes', 'Cognac', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, 0, 0),
 (251, 'x', '1986/04/10', 107, null, null, null, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 0, 1, 0),
 (252, 'm', '1973/02/18', 92, 'France', 'Île-de-France', 'Nanterre', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 0, 0, 0),
 (253, 'f', '2004/03/02', 41, 'France', null, null, null, 1, 1, 1),
 (254, 'm', '1969/12/12', 130, 'France', 'Bretagne', null, null, 1, 0, 1),
 (255, 'x', '1966/04/27', 94, 'Germany', 'Baden-Württemberg', 'Stuttgart Stuttgart-Mitte', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 0, 1, 1),
 (256, 'f', '2009/06/28', 147, null, null, null, null, 0, 1, 1),
 (257, 'x', '1980/09/16', null, 'France', 'Centre', null, null, 1, 0, 1),
 (258, 'm', '1987/06/14', 22, 'France', null, null, 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, 1, 1),
 (259, 'x', '2010/02/06', null, 'France', 'Languedoc-Roussillon', 'Alès', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 0, 1, 0),
 (260, 'f', '1953/02/08', 194, 'France', 'Auvergne', 'Clermont-Ferrand', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 1, 1, 0),
 (261, 'f', '1985/03/19', null, 'France', 'Île-de-France', 'Versailles', null, 0, 1, 1),
 (262, 'm', '1973/03/03', null, 'France', 'Provence-Alpes-Côte d''Azur', 'Digne-les-Bains', null, 0, 1, 0),
 (263, 'x', '1969/10/14', 182, 'France', null, null, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, 1, 0),
 (264, 'f', '2006/06/13', 49, 'France', 'Limousin', 'Limoges', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 0, 1, 0),
 (265, 'f', '1958/01/25', 174, 'France', 'Basse-Normandie', null, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 1, 0, 0),
 (266, 'm', '1967/04/07', null, null, null, null, null, 0, 0, 1),
 (267, 'x', '1962/03/13', 198, 'France', 'Île-de-France', 'Bonneuil-sur-Marne', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, 1, 0),
 (268, 'm', '1968/12/02', null, 'France', 'Bretagne', 'Brest', null, 1, 1, 1),
 (269, 'f', '1968/04/19', null, 'France', 'Lorraine', 'Briey', null, 1, 1, 0),
 (270, 'x', '1956/08/01', 35, 'France', 'Rhône-Alpes', 'Saint-Étienne', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0, 1, 1),
 (271, 'x', '1975/05/29', 22, 'France', 'Midi-Pyrénées', null, 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, 0, 0),
 (272, 'f', '1977/01/17', 160, 'France', 'Bretagne', 'Roscoff', null, 1, 0, 1),
 (273, 'f', '1955/07/29', null, 'France', null, null, null, 1, 0, 0),
 (274, 'm', '1953/03/03', null, 'France', null, null, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0, 1, 1),
 (275, 'f', '2008/06/24', 112, 'France', 'Pays de la Loire', 'Le Mans', null, 1, 0, 0),
 (276, 'm', '1995/12/20', 117, null, null, null, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, 1, 0),
 (277, 'f', '1992/02/26', null, null, null, null, null, 1, 1, 0),
 (278, 'x', '1952/04/02', 166, 'Germany', 'Berlin', null, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1, 0, 0),
 (279, 'x', '1963/03/31', null, 'France', 'Île-de-France', 'Rueil-Malmaison', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 0, 0, 0),
 (280, 'm', '1953/03/30', 23, 'France', 'Pays de la Loire', 'La Chapelle-sur-Erdre', null, 1, 1, 1),
 (281, 'f', '1991/12/14', null, 'France', null, null, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 0, 1, 0),
 (282, 'm', '1986/08/24', 71, 'France', 'Île-de-France', 'Évry', null, 1, 0, 0),
 (283, 'f', '1966/06/14', 41, 'France', 'Île-de-France', null, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0, 0, 1),
 (284, 'x', '1998/11/13', 40, 'France', 'Pays de la Loire', 'Nantes', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 1, 1),
 (285, 'f', '1958/10/31', null, null, null, null, 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 0, 0, 0),
 (286, 'f', '1984/02/10', null, 'France', 'Provence-Alpes-Côte d''Azur', null, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 0, 1, 1),
 (287, 'm', '1958/09/05', null, 'France', 'Île-de-France', 'Vincennes', null, 1, 0, 0),
 (288, 'm', '1971/01/28', 145, 'France', 'Centre', 'Blois', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 0, 0, 1),
 (289, 'f', '1992/07/30', 172, null, null, null, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 0, 1, 0),
 (290, 'f', '1974/01/23', 96, 'France', 'Bourgogne', 'Dijon', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, 0, 1),
 (291, 'f', '2005/09/06', 173, 'France', 'Nord-Pas-de-Calais', 'Noyelles-sous-Lens', null, 1, 0, 0),
 (292, 'x', '1989/08/07', 153, null, null, null, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 0, 1, 0),
 (293, 'x', '2004/01/29', null, 'France', null, null, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 0, 0),
 (294, 'f', '1964/03/20', null, null, null, null, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, 1, 1),
 (295, 'x', '1999/04/27', 146, 'France', 'Île-de-France', 'Paris 15', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, 1, 1),
 (296, 'x', '1993/09/02', 8, 'France', 'Limousin', 'Limoges', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 0, 0, 1),
 (297, 'f', '2000/06/19', 6, 'France', 'Île-de-France', 'Paris 12', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1, 0, 0),
 (298, 'f', '1987/03/09', 77, 'Germany', 'Berlin', 'Berlin', null, 0, 0, 0),
 (299, 'm', '1962/09/07', 194, 'France', 'Provence-Alpes-Côte d''Azur', null, null, 1, 0, 1),
 (300, 'x', '1964/06/19', 55, null, null, null, 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 0, 1, 1);